[deployment]
region = "sin"
primary_region = "sin"

[services]
  [services.web]
  internal_port = 8000
  protocol = "http"
  auto_deploy = true
  
  [services.web.http]
  force_https = true

[env]
  PORT = "8000"

[build]
  dockerfile = "Dockerfile"
